var devId = "Bearer: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDQ4MTY5MDUsInJvbGUiOiJhZG1pbiIsImlkIjoiMDQ5MTg0NDUxMzc4NTgzODg1MmQ1NTBmOTIxZDM2MjIiLCJ0ZW5hbnQiOiJ0ZW5hbnRfbXJwdGF4M29wajJ4bzZsbW9yc3cyenQybTVyeHV6ZGduZnJoaTV6c3Bmd2d1M3RycGJ0d29tenRueSsrKysrKyIsIm5hbWUiOiJhZG1pbiJ9.MxAjg6j8oY9EYo0z66yXfYrdTBFvCSwU8ld68F18VMW-zqNZApcUynRwoYuFxlqYMSgC6JBoP-x-Hm8OVzQ3Aw";
var client_secret = "AEF6Oxvmq8DMx8rL";
var client_id = "GbDmhYrijKZmAfrTIYBGkmZ7Czd0RcVR";
var host = "https://api.knurld.io/";
var enrollmentRepeats = 3;
var vocabulary = [  "Pyramid","Dallas","Canada" ];
var verificationLength = 3;
var modelId = "";
var consumerId = "";
var enrollmentId = "";
var verificationId = "";
var analyticsId = "";
var callId = "";
var threshold = 2;
var Gender = "M";
var d = new Date();
var n = d.getTime();
var username = "knurldUser" + d.getTime();
var password = "knurldPass";
var number = "12125551212";
var wav = "https://www.dropbox.com/s/tx24ztz7vjgax4v/dcp?dl=1";
var verificationVocabulary = [  "Pyramid","Dallas","Canada" ];
var password = "knurldPass";
var verificationWav="https://www.dropbox.com/s/4rd9jnq960r81zj/Canada_Dallas_Pyramid?dl=1";
var verification1="https://www.dropbox.com/s/hytfzzv3pm0evti/Canada_Pyramid_Dallas.wav?dl=1";
var verification2="https://www.dropbox.com/s/m4s52x8l4o6l2id/Canada_Dallas_Pyramid.wav?dl=1";
var verification3="https://www.dropbox.com/s/iam145el09zi29s/Dallas_Pyramid_Canada.wav?dl=1";
var verification4="https://www.dropbox.com/s/n8j6bz3lpyrz5ff/Dallas_Canada_Pyramid.wav?dl=1";
var verification5="https://www.dropbox.com/s/rps6ztxfq54a9to/Pyramid_Canada_Dallas.wav?dl=1";
var verification6="https://www.dropbox.com/s/diqggaure66nlgz/Pyramid_Dallas_Canada.wav?dl=1";
var intervalForEnrollment;
var intervalForVerification;
var fixBadGateWayError = false;
jasmine.DEFAULT_TIMEOUT_INTERVA=5000;
